workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    working_directory: ~/example_application
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME_PUBLIC_DNS "rm -rf ritaobrien/ExampleApplication/;git clone https://github.com/RONCI/ExampleApplication.git; source ExampleApplication/deploy.sh"
